# Generated by Django 3.0.3 on 2020-02-26 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_model', models.CharField(max_length=256)),
                ('auto_class', models.CharField(choices=[('car', 'car'), ('truck', 'truck'), ('suv', 'suv')], max_length=32)),
                ('num_doors', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sold', models.DateTimeField()),
                ('sale_amount', models.IntegerField()),
                ('autos', models.ManyToManyField(related_name='sales', to='dealerships.Auto')),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales', to='people.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Dealership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('max_fleet_count', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('general_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_dealerships', to='people.Person')),
                ('sales_reps', models.ManyToManyField(related_name='dealerships', to='people.Person')),
            ],
        ),
        migrations.AddField(
            model_name='auto',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dealerships.Dealership'),
        ),
    ]
