# Generated by Django 3.0.3 on 2020-02-27 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dealerships', '0002_dealership_web_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealership',
            name='web_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='admin_dealerships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dealership',
            name='web_users',
            field=models.ManyToManyField(blank=True, related_name='web_dealerships', to=settings.AUTH_USER_MODEL),
        ),
    ]
